#!/usr/bin/env bash

sudo add-apt-repository -y ppa:dotnet/backports

sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive \
  sudo apt-get install -y --no-install-recommends \
  dotnet-sdk-8.0 \
  dotnet-sdk-9.0
