#!/usr/bin/env bash

sudo add-apt-repository -y ppa:git-core/ppa

# Packagecloud doesn't provide git-lfs for every Ubuntu release – check if it's
# available before attempting to use it. Ubuntu provides git-lfs packages too;
# Packagecloud is more up-to-date, so we prefer those...

lsb_id=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
lsb_codename=$(lsb_release -cs)

if
  wget --spider -nv -q \
    "https://packagecloud.io/github/git-lfs/$lsb_id/dists/$lsb_codename/InRelease"
then
  curl -s \
    https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh |
    sudo bash
fi

arch=$(dpkg --print-architecture)

curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg |
  sudo dd of=/usr/share/keyrings/github-cli.gpg

echo \
  deb [arch="$arch" signed-by=/usr/share/keyrings/github-cli.gpg] \
  https://cli.github.com/packages stable main |
  sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
  gh \
  git \
  git-filter-repo \
  git-lfs
