#!/usr/bin/env bash

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
  gnome-system-monitor \
  gnome-text-editor \
  gnome-tweaks \
  ssh-askpass-gnome \
  pinentry-gnome3 \
  zenity

sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  nautilus

{
  echo '🔐 Pin-entry and ask-pass alternatives:'
  echo -n '   - '
  readlink -f /etc/alternatives/pinentry
  echo -n '   - '
  readlink -f /etc/alternatives/ssh-askpass
} >&3
