#!/usr/bin/env bash

if ! [ -d "$HOME/.pyenv" ]; then

  if ! [[ $PATH =~ (^|:)"$HOME/.pyenv"(:|$) ]]; then
    echo "  ⚠️ Add \"📂 $HOME/.pyenv\" to PATH... " >&3
    PATH="$PATH:$HOME/.pyenv"
  fi

  sudo apt-get update

  sudo DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    build-essential \
    curl \
    libbz2-dev \
    libffi-dev \
    liblzma-dev \
    libncursesw5-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libxml2-dev \
    libxmlsec1-dev \
    tk-dev \
    xz-utils \
    zlib1g-dev

  curl https://pyenv.run | bash

fi
