#!/usr/bin/env bash

xauth add :0 . "$(mcookie)"

# Symlink ~/Desktop and ~/Downloads

if [ ! -e ~/Desktop ]; then
  if [ ! -d /mnt/d/Thijs/Desktop ]; then
    echo '  ⛔ Skipping "🔗 ~/Desktop" — target not found...' >&3
    return 0
  fi
  ln -s /mnt/d/Thijs/Desktop ~/Desktop
  echo "  🔗 ~/Desktop ← /mnt/d/Thijs/Desktop" >&3
fi

if [ ! -e ~/Downloads ]; then
  if [ ! -d /mnt/d/Thijs/Desktop ]; then
    echo '  ⛔ Skipping "🔗 ~/Downloads" — target not found...' >&3
    return 0
  fi
  ln -s /mnt/d/Thijs/Downloads ~/Downloads
  echo "  🔗 ~/Downloads ← /mnt/d/Thijs/Downloads" >&3
fi
