#!/usr/bin/env bash

if [ ! -e ~/.env ]; then
  cp "${base:?}/.env.default" ~/.env
fi

{
  printf '📢 Inspect "~/.env" and ensure the values defined '
  printf 'are appropriate for your system...'
} >&3
