#!/usr/bin/env bash

if ! command -v locate; then
  echo '  ⛔ Skipping "🔗 ~/.ssh/config" — locate not present...' >&3
  return 0
fi

if [ ! -e ~/.ssh/config ]; then

  locate_ssh="$(locate -l 1 -r '/mnt/d/.*/WSL/.ssh/config$')"

  if [ -z "$locate_ssh" ]; then
    echo '  ⛔ Skipping "🔗 ~/.ssh/config" — target not found...' >&3
    return 0
  fi

  chmod 0600 "$locate_ssh"
  ln -s "$locate_ssh" ~/.ssh/config
  echo "  🔗  ~/.ssh/config ← $locate_ssh" >&3

fi
