#!/usr/bin/env bash

# Run pyenv update check weekly via anacron

if
  [ -e ~/.anacron/etc/anacrontab ] &&
    [ ! -e ~/.anacron/scripts/pyenv-update-check.sh ]
then

  if ! [ -d "$HOME/.pyenv" ]; then
    printf '⛔ Skipping "📄 scripts/pyenv-update-check.sh" — ' >&3
    printf 'pyenv not properly configured...\n' >&3
    return 0
  fi

  mkdir -p ~/.anacron/scripts
  ln -s -r "${base:?}/scripts/pyenv-update-check.sh" \
    ~/.anacron/scripts/pyenv-update-check.sh

  echo "7  0  pyenv-update-check  $HOME/.anacron/scripts/pyenv-update-check.sh" \
    >> ~/.anacron/etc/anacrontab

fi
