#!/usr/bin/env bash

# Backup via rclone

if [ ! -e ~/.rclone ]; then

  if
    ! command -v rclone &> /dev/null ||
      ! rclone listremotes | grep onedrive:
  then
    {
      printf '⛔ Skipping "📄 scripts/rclone.sh" — '
      printf 'rclone not properly configured...\n'
    } >&3
    return 0
  fi

  ln -s -r "${base:?}/scripts/rclone.sh" ~/.rclone

  # Run daily via anacron

  if [ -e ~/.anacron/etc/anacrontab ]; then
    echo "1  0  rclone-backup  $HOME/.rclone" >> ~/.anacron/etc/anacrontab
  fi

fi
