#!/usr/bin/env bash

if [ ! -e "$(readlink -f /usr/local/bin/usbip)" ]; then

  result=$(
    sudo update-alternatives --install /usr/local/bin/usbip usbip \
      "$(find /usr/lib/linux-tools/*/usbip | tail -n 1)" 20 2> /dev/null
  )

  if [ -n "$result" ]; then
    echo "✅ $(tail -n 1 <<< "$result")" >&3
  fi

fi

# Setup cached Yubikey state-tracking

if [[ ! -e ~/.local/bin/yubikey-cache-state.sh ]]; then
  ln -s -r "${base:?}/.local/bin/yubikey-cache-state.sh" \
    ~/.local/bin/yubikey-cache-state.sh
fi

for file in "${base:?}"/.config/systemd/user/yubikey-cache-state.*; do
  if [[ ! -e ~/.config/systemd/user/"${file##*/}" ]]; then
    mkdir -p ~/.config/systemd/user
    ln -s -r "${base:?}/.config/systemd/user/${file##*/}" \
      ~/.config/systemd/user/"${file##*/}"
  fi
done

systemctl --user enable --now yubikey-cache-state.timer

# Install powerline-go Yubikey-state segment

if [[ ! -e ~/.local/bin/powerline-go-yubikey ]]; then
  ln -s -r "${base:?}/.local/bin/powerline-go-yubikey" \
    ~/.local/bin/powerline-go-yubikey
fi
