#!/usr/bin/env bash

gsettings set org.gnome.desktop.interface text-scaling-factor 1.33

gsettings set org.gnome.desktop.interface document-font-name \
  'Ubuntu Sans Medium 11 @wght=500'
gsettings set org.gnome.desktop.interface font-name \
  'Ubuntu Sans Medium 11 @wght=500'
gsettings set org.gnome.desktop.interface monospace-font-name \
  'Ubuntu Sans Mono Medium 11 @wght=500'

gsettings set org.gnome.desktop.interface monospace-font-name \
  'Ubuntu Sans Mono Medium 11 @wght=500'
gsettings set org.gnome.desktop.interface monospace-font-name \
  'Ubuntu Sans Mono Medium 11 @wght=500'

gsettings set org.gnome.desktop.interface font-antialiasing rgba
gsettings set org.gnome.desktop.interface font-hinting full

gsettings set org.gnome.desktop.interface clock-format 24h
