#!/usr/bin/env bash

# Mask all GPG agent related units – the RPis use a socket forwarded from the
# local machine instead. Unintentionally starting gpg-agent messes with this
# setup.
# Note that the "no-autostart" in "📄 gpg.conf" makes most of the difference.
# The RPIs generally don't start gpg-agent via systemd (ie, have it running
# with "--supervised"), instead a "--daemon" is started by the gpg binary
# itself. The below is thus mainly for good measure...

systemctl --user mask \
  gpg-agent.service \
  gpg-agent.socket \
  gpg-agent-ssh.socket \
  gpg-agent-extra.socket \
  gpg-agent-browser.socket
