#!/usr/bin/env bash

set -euo pipefail

arch=$(dpkg --print-architecture)
# <https://xkcd.com/927/>
if [[ $arch == 'arm64' ]]; then arch=aarch64; fi

base=https://github.com/fastfetch-cli/fastfetch/releases/download
: "${version:=2.44.0}"

wget -nv "${base}/${version}/fastfetch-linux-${arch}.deb"
sudo dpkg -i "fastfetch-linux-${arch}.deb"

rm -f "fastfetch-linux-${arch}.deb"

command -v fastfetch &&
  echo "⚙️ Installed $(fastfetch --version)" >&3
