#!/usr/bin/env bash

set -euo pipefail

: "${version:=v0.0.7-1}"
: "${GOPATH:="$HOME/.local/go"}"
export GOPATH

git clone https://gitlab.com/ribtoks/tdg.git
cd tdg || exit 1

git checkout "tags/$version"

# Add "triple-X" as one of the comment prefixes
git apply --ignore-space-change --ignore-whitespace - \
  <<- EOF || : # "or true" to prevent "set -e" from exiting the script
diff --git a/pkg/tdglib/todogenerator.go b/pkg/tdglib/todogenerator.go
index faca56a..7e3951a 100644
--- a/pkg/tdglib/todogenerator.go
+++ b/pkg/tdglib/todogenerator.go
@@ -27,7 +27,7 @@ const (
 )

 var (
-       commentPrefixes        = [...]string{"TODO", "FIXME", "BUG", "HACK"}
+       commentPrefixes        = [...]string{"TODO", "FIXME", "BUG", "HACK", "XXX"}
        sourceControlSystems   = [...]string{".git", ".hg", ".svn", ".tf", ".bzr"}
        emptyRunes             = [...]rune{}
        categoryIniKey         = "category"
EOF

export GOFLAGS="-mod=vendor"
go build -o "$GOPATH/bin/tdg" cmd/tdg/*

command -v tdg && tdg -root cmd/tdg &&
  echo "⚙️ Installed tdg $version" >&3
