#!/usr/bin/env bash

# Based on:
#   <https://github.com/wslutilities/wslu/blob/v4.1.3/extras/scripts/wslu-install>

: "${version:=v4.1.3}"

build_dir=$(mktemp --tmpdir --directory wslu-install.XXXX)
cd "$build_dir" || exit 1

git clone https://github.com/wslutilities/wslu "$build_dir"
git co -b "$version" "$version"

bash configure.sh
make
sudo make install

cd ~/ || exit 1
rm -rf "$build_dir"

# Register "wslview" as web-browser
sudo update-alternatives \
  --install /usr/bin/www-browser www-browser /usr/bin/wslview 50
sudo update-alternatives \
  --install /usr/bin/x-www-browser x-www-browser /usr/bin/wslview 50

command -v wslsys &&
  echo "⚙️ Installed $(wslsys -v)" >&3
