#!/usr/bin/env bash

set -euo pipefail

arch=$(dpkg --print-architecture)
base=https://github.com/justjanne/powerline-go/releases/download
: "${version:=v1.24}"

wget -nv -O ~/.local/bin/powerline-go \
  "${base}/${version}/powerline-go-linux-${arch}"
chmod +x ~/.local/bin/powerline-go

command -v powerline-go && powerline-go -modules user -mode flat && printf '\n'
