#!/usr/bin/env bash

set -euo pipefail

arch=$(dpkg --print-architecture)
base=https://github.com/mvdan/sh/releases/download
: "${version:=v3.7.0}"

wget -nv -O ~/.local/bin/shfmt \
  "${base}/${version}/shfmt_${version}_linux_${arch}"
chmod +x ~/.local/bin/shfmt

command -v shfmt && shfmt --version
