#!/usr/bin/env bash

# If we're not showing the full MOTD, show the header line instead – *except*
# when the first argument passed to Bash starts with 'ssh '. This is to ensure
# the header doesn't show twice (once local, once for the SSH-session) in case
# we use "bash -i -c $0 'ssh user@host'" to open an SSH-session (which in itself
# is a slight hack to make the below work).

if [ -z "$MOTD_SHOWN" ] && [[ $0 != 'ssh '* ]]; then
  . /etc/update-motd.d/00-header
  printf "\n\n"
fi
