#!/usr/bin/env bash

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export PIP_REQUIRE_VIRTUALENV=true

dotenv() {
  set -a
  # shellcheck disable=SC1090,SC1091
  if [ -f "$1" ]; then
    source "$1"
  elif [ -f .env ]; then
    source .env
  fi
  set +a
}

# Export all environment variables defined in ~/.env
dotenv ~/.env
