#!/usr/bin/env bash

WSL_IP=
pattern="IP Address:\s+\K[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"

for interface in "Ethernet (ThinkPad)" "WiFi"; do
  if WSL_IP=$(cmd.exe /c "netsh interface ip show addresses \"$interface\"" \
      2> /dev/null | grep -oP "$pattern") ; then
    break
  fi
done

export WSL_IP
