#!/usr/bin/env bash

function _powerline_ps1() {
  PS1="$(powerline-go -error $? -jobs "$(jobs -p | wc -l)")"
  PS1+="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]"
}

if [ "$TERM" != "linux" ] && [ -f "$HOME/.local/bin/powerline-go" ]; then
  PROMPT_COMMAND="_powerline_ps1${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi
