#!/usr/bin/env bash

# GPG-Agent
GPG_TTY=$(tty)
export GPG_TTY

# Use GPG-Agent for SSH
# https://wiki.archlinux.org/index.php/GnuPG#SSH_agent

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then

  SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
  export SSH_AUTH_SOCK

  gpg-connect-agent updatestartuptty /bye &> /dev/null

fi
