#!/usr/bin/env bash

# Only export these when an X11 server is running on the WSL host. Otherwise,
# certain things depending on the combination of X11 and D-Bus might start to
# complain...

if [ -n "$WSL_IP" ] && timeout 0.1 nc -z "$WSL_IP" 6000 &> /dev/null ; then

  LIBGL_ALWAYS_INDIRECT=1
  DISPLAY="$WSL_IP":0.0
  export \
    LIBGL_ALWAYS_INDIRECT \
    DISPLAY

  if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] ; then
    if eval "$(dbus-launch --sh-syntax --exit-with-x11)" ; then
      return
    fi
  fi

  # Unset DISPLAY if D-Bus fails to launch
  unset DISPLAY

fi
