#!/usr/bin/env bash

# X11 (via VcXsrv)
# Only export these when VcXsrv is running; otherwise many things depending on
# D-Bus (e.g. Python, screenfetch) will start to complain...

if timeout 0.1 nc -z t14s.sgraastra 6000 &> /dev/null ; then

    LIBGL_ALWAYS_INDIRECT=1
    DISPLAY=t14s.sgraastra:0.0
    export \
      LIBGL_ALWAYS_INDIRECT \
      DISPLAY

    if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] ; then
        eval "$(dbus-launch --sh-syntax --exit-with-x11)"
    fi

fi
