#!/usr/bin/env bash

alias l='ls -lhF --group-directories-first'
alias ll='ls -alhF --group-directories-first'

alias '??'='gh copilot suggest -t shell'

# If "docker-compose" is available, map it to "docker compose"
docker() {
  if [[ ${1,,} == compose ]] && command -v docker-compose &> /dev/null; then
    shift
    command docker-compose "$@"
  else
    command docker "$@"
  fi
}

gh() {
  # If "act" is available, map it to "gh act"
  if [[ ${1,,} == act ]] && command -v act &> /dev/null; then
    shift
    command act "$@"
  else
    command gh "$@"
  fi
}
