#!/usr/bin/env bash

alias l='ls -lhF --group-directories-first'
alias ll='ls -alhF --group-directories-first'

alias '??'='gh copilot suggest -t shell'

# If "docker-compose" is available, map it to "docker compose"
docker() {
  if [[ ${1,,} == compose ]] && command -v docker-compose &> /dev/null; then
    shift
    command docker-compose "$@"
  else
    command docker "$@"
  fi
}

# If "gnome-text-editor" is available, map it to "gedit" and fork
gedit() {
  if command -v gnome-text-editor &> /dev/null; then
    (
      gnome-text-editor "$@" &> /dev/null &
      disown
    )
  fi
}

gh() {
  # If "act" is available, map it to "gh act"
  if [[ ${1,,} == act ]] && command -v act &> /dev/null; then
    shift
    command act "$@"
  else
    command gh "$@"
  fi
}

git() {

  if [[ $(type -t _yubikey-git) == "function" ]]; then
    _yubikey-git "$@"
  else
    command git "$@"
  fi

  git_result=$?

  # When doing a "simple" clone; attempt to change into the directory that was
  # just cloned...

  if [[ ${1,,} == clone && ${2: -4} == ".git" ]]; then

    repoName=${2##*/}
    repoName=${repoName%.git}

    if [[ $git_result -eq 0 && -d $repoName ]]; then
      cd "$repoName" || return
    fi

  fi
}
