#!/usr/bin/env bash

# Don't duplicate on SSH (see 00-header) or for non-"standalone" terminals
if [[ $0 != 'ssh '* ]] && [ -z "$TERM_PROGRAM" ]; then

  # Workaround missing new-lines on SSH
  if [ "$MOTD_SHOWN" == "pam" ]; then
    printf "\n\n"
  fi

  # Prevent neofetch from showing output one line at a time
  printf "%s\n" "$(neofetch)"

fi
