#!/usr/bin/env bash

# Display fastfetch only as part of an already shown (MOTD) header

if [ -n "$HEADER_SHOWN" ] && command -v fastfetch &> /dev/null; then

  printf "\n"
  fastfetch --size-ndigits 1
  printf "\n"

fi
