#!/usr/bin/env bash

if command -v mcfly &> /dev/null; then

  export MCFLY_FUZZY=2
  export MCFLY_RESULTS=$(($(tput lines) - 4))
  export MCFLY_INTERFACE_VIEW=BOTTOM

  eval "$(mcfly init bash)"

  # Workaround for <https://github.com/cantino/mcfly/issues/240>

  if [[ ${BASH_VERSINFO[0]} -eq 5 && ${BASH_VERSINFO[1]} -lt 2 ]]; then

    function _mcfly_workaround() {
      rc=$?
      stty echo icrnl icanon
      return $rc
    }

    PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND;}_mcfly_workaround"

  fi

fi
