#!/usr/bin/env bash

function _powerline_ps1() {
  PS1="$(powerline-go -error $? -jobs "$(jobs -p | wc -l)")"
  PS1+="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]"
}

if [ "$TERM" != "linux" ] && command -v powerline-go &> /dev/null; then
  PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND;}_powerline_ps1"
fi
