#!/usr/bin/env bash

# If we're not showing the full MOTD, show a header line instead - *except* when
# the first argument passed to Bash contains an '@'. This is to ensure the
# header doesn't show twice (once local, once for the SSH-session) in case I use
# "bash -i -c 'ssh $0' user@host" to open an SSH-session

if [ -z "$MOTD_SHOWN" ] && [[ $0 != *'@'* ]]; then
  . /etc/update-motd.d/00-header
  printf "\n"
fi
