#!/usr/bin/env bash

# Don't show when directly starting a SSH session (see 00-header) or for
# non-"standalone" terminals
if [[ $0 != 'ssh '* ]] && [ -z "$TERM_PROGRAM" ]; then

  # Prevent neofetch from outputting one line at a time
  printf "\n%s\n" "$(neofetch)"

fi
