#!/usr/bin/env bash

if ! pgrep -x rsyslogd > /dev/null || ! pgrep -x cron > /dev/null; then

  count=0

  if sudo /usr/sbin/service rsyslog start > /dev/null;  then ((count++)); fi
  if sudo /usr/sbin/service cron start > /dev/null;     then ((count++)); fi
  if sudo /usr/sbin/service anacron start > /dev/null;  then ((count++)); fi
  if sudo /usr/sbin/service dbus start > /dev/null;     then ((count++)); fi

  echo "Started $count service(s)."

fi
