#!/usr/bin/env bash

if [ ! -e ~/.bashrc.d ]; then
  ln -s -r "${base:?}/.bashrc.d" ~/.bashrc.d
fi

if ! grep -q '^# Source parts from ~/\.bashrc\.d$' "${bashrc:?}"; then

  cat <<- 'EOF' >> "${bashrc:?}"
		# Source parts from ~/.bashrc.d

		for file in "$HOME"/.bashrc.d/**; do

			if [[ -x "$file" ]]; then
				source "$file"
			fi

		done
	EOF
  # N.B., mind the tab-indentation inside the heredoc!

fi
