#!/usr/bin/env bash

mkdir -p ~/.config

if [ ! -e ~/.config/gh/config.yml ]; then
  mkdir -p ~/.config/gh
  ln -s -r "${base:?}/.config/gh/config.yml" \
    ~/.config/gh/config.yml
fi

if [ ! -e ~/.config/fastfetch/config.jsonc ]; then
  mkdir -p ~/.config/fastfetch
  ln -s -r "${base:?}/.config/fastfetch/config.jsonc" \
    ~/.config/fastfetch/config.jsonc
fi
