#!/usr/bin/env bash

mkdir -p ~/.config

if [ ! -e ~/.config/gh/config.yml ]; then
  mkdir -p ~/.config/gh
  ln -s -r "${base:?}/.config/gh/config.yml" \
    ~/.config/gh/config.yml
fi

if [ ! -e ~/.config/fastfetch/config.jsonc ]; then
  mkdir -p ~/.config/fastfetch
  ln -s -r "${base:?}/.config/fastfetch/config.jsonc" \
    ~/.config/fastfetch/config.jsonc
fi

# Copy in htop's settings – as its parsing is quite primitive, don't symlink to
# avoid issues with different versions of htop

if [ ! -e ~/.config/htop/htoprc ]; then
  mkdir -p ~/.config/htop
  cp "${base:?}/.config/htop/htoprc" \
    ~/.config/htop/htoprc
fi
