#!/usr/bin/env bash

if [ ! -e ~/.config/powerline-go/config.json ]; then
  mkdir -p ~/.config/powerline-go
  ln -s -r "${base:?}/.config/powerline-go/config-wsl.json" \
    ~/.config/powerline-go/config.json
fi
