#!/usr/bin/env bash

if [ ! -e ~/.rclone ]; then

  if
    ! command -v rclone &> /dev/null ||
    ! rclone listremotes | grep onedrive:
  then
    echo ' |-> ⚠️ skipping "📄 ~/.rclone" — rclone not properly configured...'
    return 0
  fi

  # Run daily via anacron

  if [ -e ~/.anacron/etc/anacrontab ]; then

    ln -s -r "${base:?}/scripts/.rclone" ~/.rclone
    echo "1  0  rclone-backup  $HOME/.rclone" >> ~/.anacron/etc/anacrontab

  fi

fi
