#!/usr/bin/env bash

if [ ! -e "$(readlink -f /usr/local/bin/usbip)" ]; then

  result=$(
    sudo update-alternatives --install /usr/local/bin/usbip usbip \
      "$(find /usr/lib/linux-tools/*/usbip | tail -n 1)" 20 2> /dev/null
  )

  if [ -n "$result" ]; then
    echo "  ✅ $(tail -n 1 <<< "$result")" >&3
  fi

fi
