#!/usr/bin/env bash

sudo chmod --silent -x /etc/update-motd.d/10-help-text || true
sudo chmod --silent -x /etc/update-motd.d/50-landscape-sysinfo || true
sudo systemctl mask motd-news.service || true

# Disable "Wi-Fi rfkill"-warning (RPi OS)

if [ -s /etc/profile.d/wifi-check.sh ] ; then
  sudo mv /etc/profile.d/{wifi-check.sh,.wifi-check.sh} || true
fi

# Empty out the static message of the day — an empty file is intentionally left
# behind: This ensures there are sufficient newlines between the various other
# parts of the MoTD.

echo "" | sudo tee /etc/motd > /dev/null
