#!/usr/bin/env bash

sudo chmod --silent -x /etc/update-motd.d/10-help-text || true

landscape_sysinfo=/etc/update-motd.d/50-landscape-sysinfo
if [ -L "$landscape_sysinfo" ]; then
  sudo rm "$landscape_sysinfo"
elif [ -f "$landscape_sysinfo" ]; then
  sudo chmod --silent -x "$landscape_sysinfo"
fi

# Silence the daily ".hushlogin"-notification – without harming the rest of the
# script, as that's responsible for generating ~/.motd_shown...

sudo sed -i "s/^\(\s*\)echo /\1: #echo /g" /etc/profile.d/update-motd.sh

# Disable dynamic MOTD (and its systemd units for good measure)

sudo sed -i "s/^ENABLED=1\+/ENABLED=0/g" /etc/default/motd-news

if systemctl list-unit-files motd-news.service; then
  sudo systemctl mask motd-news.service || true
  sudo systemctl mask motd-news.timer || true
fi

# Disable "Wi-Fi rfkill"-warning (RPi OS)

if [ -s /etc/profile.d/wifi-check.sh ]; then
  sudo mv /etc/profile.d/{wifi-check.sh,.wifi-check.sh} || true
fi

# Empty out the static message of the day — an empty file is intentionally left
# behind: This ensures there are sufficient newlines between the various other
# parts of the MOTD.

echo "" | sudo tee /etc/motd > /dev/null
