#!/usr/bin/env bash

sudo add-apt-repository ppa:oibaf/graphics-drivers

sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
  libvulkan1 \
  mesa-vulkan-drivers \
  mesa-utils \
  vulkan-tools

sudo update-pciids
