#!/usr/bin/env bash

sudo add-apt-repository -y ppa:git-core/ppa

curl -s \
  https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh |
  sudo bash

arch=$(dpkg --print-architecture)

curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg |
  sudo dd of=/usr/share/keyrings/github-cli.gpg

echo \
  deb [arch="$arch" signed-by=/usr/share/keyrings/github-cli.gpg] \
  https://cli.github.com/packages stable main |
  sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
  gh \
  git \
  git-filter-repo \
  git-lfs
