#!/usr/bin/env bash

arch=$(dpkg --print-architecture)
lsb_id=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
lsb_codename=$(lsb_release -cs)
lsb_release=$(lsb_release -rs)

curl -fsSL https://packages.microsoft.com/keys/microsoft.asc |
  sudo gpg --dearmor --yes -o /usr/share/keyrings/microsoft.gpg

echo \
  deb [arch="$arch" signed-by=/usr/share/keyrings/microsoft.gpg] \
  "https://packages.microsoft.com/$lsb_id/$lsb_release/prod" "$lsb_codename" main |
  sudo tee /etc/apt/sources.list.d/microsoft.list > /dev/null

# Implement "Scenario 1" from <https://github.com/dotnet/core/issues/7713>:
# Prefer packages.microsoft.com for .NET (and PowerShell) packages

sudo tee /etc/apt/preferences.d/10-powershell > /dev/null << 'EOF'
Package: *
Pin: origin "packages.microsoft.com"
Pin-Priority: 1001
EOF

sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive \
  sudo apt-get install -y \
  dotnet-sdk-8.0
