#!/usr/bin/env bash

sudo add-apt-repository ppa:git-core/ppa
sudo add-apt-repository ppa:ondrej/php
sudo add-apt-repository ppa:yubico/stable

curl -sSL https://packages.microsoft.com/keys/microsoft.asc | \
  sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
sudo apt-add-repository https://packages.microsoft.com/ubuntu/22.04/prod

curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
