#!/usr/bin/env bash

sudo apt-get update

if ! commad -v snap; then

  sudo DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    snapd

fi

# Install XDG Desktop Portal only when running a local display server (ie, when
# _not_ forwarding X11 over SSH) – for remote devices this would mostly be
# overkill...

if [[ ! $DISPLAY =~ localhost ]]; then

  sudo DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    xdg-desktop-portal \
    xdg-desktop-portal-gtk

fi
