#!/usr/bin/env bash

sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
  python-is-python3 \
  python3-pip \
  python3-venv

if ! [[ $PATH =~ (^|:)"$HOME/.local/bin"(:|$) ]]; then
  echo "  ⚠️ Add \"📂 $HOME/.local/bin\" to PATH... " >&3
  PATH="$PATH:$HOME/.local/bin"
fi

# Ignore the warning in /usr/share/doc/python3.11/README.venv – we want these
# packages to be user-managed, not system-managed...

(
  export PIP_REQUIRE_VIRTUALENV=false
  export PIP_BREAK_SYSTEM_PACKAGES=1
  pip install --upgrade --user pip
  pip install --upgrade --user setuptools
)
