#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install neofetch
sudo apt-get install direnv

# Node / NPM

sudo apt-get install nodejs

npm config set prefix ~/.local/
npm install -g npm

# PowerShell / dotNet
#
# Implement "Scenario 2" from <https://github.com/dotnet/core/issues/7713>.
# Prefer dotnet-sdk to come from Ubuntu instead of PMC; PowerShell comes from
# PMC.

sudo tee /etc/apt/preferences.d/10-powershell > /dev/null << 'EOF'
Package: *
Pin: origin "packages.microsoft.com"
Pin-Priority: 400
EOF

sudo apt-get update
sudo apt-get install powershell
sudo apt-get install dotnet-sdk
