#!/usr/bin/env bash

if ! [[ $PATH =~ (^|:)"$HOME/.local/bin"(:|$) ]]; then
  echo "  ⚠️ Add \"📂 $HOME/.local/bin\" to PATH... " >&3
  PATH="$PATH:$HOME/.local/bin"
fi

# See /usr/share/doc/python3.11/README.venv

echo "  🐍 pipx" >&3
(
  export PIP_REQUIRE_VIRTUALENV=false
  export PIP_BREAK_SYSTEM_PACKAGES=1
  pip install --user pipx
)

echo "  🐍 pre-commit" >&3
pipx install pre-commit

echo "  🐍 yamllint" >&3
pipx install yamllint

echo "  🐍 pip-tools (pip-compile & pip-sync)" >&3
pipx install pip-tools
