#!/usr/bin/env bash

sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
  bsd-mailx \
  btop \
  jq \
  net-tools \
  nullmailer

echo '  📢 "nullmailer" requires manual configuration... ' >&3
