#!/usr/bin/env bash

if [ ! -e ~/.bashrc.d ]; then
  ln -s -r "${base:?}/.bashrc.d" ~/.bashrc.d
fi

if ! grep -q '^# Source parts from ~/\.bashrc\.d ' ~/.bashrc; then

  cat <<- 'EOF' >> ~/.bashrc

		# Source parts from ~/.bashrc.d (only when _not_ sourced from ~/.profile)
		if [ -z "$profile_sourced" ]; then
		  for file in "$HOME"/.bashrc.d/**; do
		    if [[ -x $file ]]; then source "$file"; fi
		  done
		fi

	EOF
  # N.B., mind the tab-indentation inside the heredoc! It's intentionally mixed
  # tabs and spaces, to ensure the end-result is indented correctly...

fi
