#!/usr/bin/env sh

export LIBVA_DRIVER_NAME=d3d12

if command -v wslvar > /dev/null 2>&1; then

  WSL_LOCAL_APPDATA="$(wslpath "$(wslvar LOCALAPPDATA)")"
  if [ -n "$WSL_LOCAL_APPDATA" ]; then
    export WSL_LOCAL_APPDATA
  fi

fi
